### ISSUE TITLE
Add tests to pre-existing cases

### ISSUE THREAD

**Issue by warisa-r** [warisa-r/ShockwaveDetection.jl#3]
Simply implement tests or analysis functions

- [ ] Investigate the properties of shock waves using relations and equations from theories in `shock_analysis`

Test series should be implemented regarding this

**Comment by aj-fleming** [comment]
[Comparison of several numerical methods](http://www.thevisualroom.com/sods_test_problem.html)

[Analytical solution to the right-moving shock tube](https://en.wikipedia.org/wiki/Sod_shock_tube#Analytic_derivation)

**Comment by warisa-r** [comment]
Thank you very much! @aj-fleming. We will look into this!

**Comment by warisa-r** [comment]
I see it now. Sorry for the repeated question!
