### ISSUE TITLE
Better parameter initialization for the fits

### ISSUE THREAD

**Issue by elenaiwnw** [warisa-r/ShockwaveDetection.jl#8]
Deadline: 08.09.

**Comment by warisa-r** [comment]
Have u tested the runtime? Can u see what happens in the shock orb case? Especially in last frames, does better parameter initialization fit the segment of the circle to last frames or do they still fit parabolas.

**Comment by warisa-r** [comment]
Make this an argument in `detect` function

**Comment by elenaiwnw** [comment]
Key changes: 
1. The code now includes an argument 'make_initial_guess::Bool' for functions 'fit_shock_cluster', 'fit_shock_clusters', and 'fit_shock_clusters_over_time' to determine if better initial guesses should be used.
2. Helper functions like 'compute_better_initial_guess' and 'generate_random_initial_guess' handle parameter initialization.
3. in pipeline.jl: directly added a 'make_intiial_guess' parameter to 'detect'' and pass it to 'fit_shock_clusters_over_time'
Updates -> Still working on it.

**Comment by warisa-r** [comment]
The initial guess should be tested and analyze in sandbox first before getting implemented in the package since the efficiency of the guess algorithm should be thoroughly analyzed

**Comment by warisa-r** [comment]
Done
